---
# CNI verification tasks
# These tasks are intended to be run after nodes are ready

- name: Wait for Flannel pods to be ready
  ansible.builtin.shell: |
    set -o pipefail
    kubectl get pods -n kube-flannel -o jsonpath='{.items[*].status.phase}' | grep -v Running | wc -l
  become_user: "{{ ansible_user }}"
  become: false
  register: cni_flannel_pod_status
  until: cni_flannel_pod_status.stdout == "0"
  retries: 30
  delay: 10
  changed_when: false
  failed_when: false

- name: Wait for Flannel DaemonSet to be ready
  ansible.builtin.shell: |
    READY=$(kubectl get daemonset -n kube-flannel kube-flannel-ds -o jsonpath='{.status.numberReady}' 2>/dev/null || echo "0")
    DESIRED=$(kubectl get daemonset -n kube-flannel kube-flannel-ds -o jsonpath='{.status.desiredNumberScheduled}' 2>/dev/null || echo "1")
    if [ "$READY" = "$DESIRED" ] && [ "$READY" -gt "0" ]; then
      echo "Flannel DaemonSet is ready: $READY/$DESIRED"
      exit 0
    else
      echo "Flannel DaemonSet not ready: $READY/$DESIRED"
      exit 1
    fi
  become_user: "{{ ansible_user }}"
  become: false
  register: cni_flannel_daemonset_status
  until: cni_flannel_daemonset_status.rc == 0
  retries: 30
  delay: 10
  changed_when: "'Flannel DaemonSet is ready' in cni_flannel_daemonset_status.stdout"
  failed_when: false

- name: Wait for all nodes to be ready
  ansible.builtin.shell: |
    set -o pipefail
    NOT_READY=$(kubectl get nodes --no-headers | grep -v Ready | wc -l)
    if [ "$NOT_READY" -eq "0" ]; then
      echo "All nodes are ready"
      kubectl get nodes
      exit 0
    else
      echo "Waiting for nodes to be ready - $NOT_READY nodes not ready"
      kubectl get nodes
      exit 1
    fi
  become_user: "{{ ansible_user }}"
  become: false
  register: cni_nodes_ready_status
  until: cni_nodes_ready_status.rc == 0
  retries: 60
  delay: 10
  changed_when: "'All nodes are ready' in cni_nodes_ready_status.stdout"
  failed_when: false

- name: Wait for CoreDNS pods to be ready
  ansible.builtin.shell: |
    set -o pipefail
    NOT_READY=$(kubectl get pods -n kube-system -l k8s-app=kube-dns --no-headers | grep -v Running | wc -l)
    if [ "$NOT_READY" -eq "0" ]; then
      echo "CoreDNS pods are ready"
      kubectl get pods -n kube-system -l k8s-app=kube-dns
      exit 0
    else
      echo "Waiting for CoreDNS pods - $NOT_READY pods not ready"
      kubectl get pods -n kube-system -l k8s-app=kube-dns
      exit 1
    fi
  become_user: "{{ ansible_user }}"
  become: false
  register: cni_coredns_status
  until: cni_coredns_status.rc == 0
  retries: 30
  delay: 10
  changed_when: "'CoreDNS pods are ready' in cni_coredns_status.stdout"
  failed_when: false
