---
- name: Test Ansible automation on worker nodes
  hosts: workers
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Ensure required directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /opt/cni/bin
        - /etc/wireguard
        - /etc/kubernetes

  roles:
    - common

  post_tasks:
    - name: Verify CNI plugins installation
      ansible.builtin.command: ls /opt/cni/bin/loopback
      register: cni_check
      changed_when: false

    - name: Display installation success
      ansible.builtin.debug:
        msg: "CNI plugins successfully installed: {{ cni_check.stdout_lines }}"
      when: cni_check.rc == 0
