---
- name: Test Standardized Worker Configuration
  hosts: workers
  become: true
  gather_facts: true

  tasks:
    - name: Verify both workers use wg0 interface
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: WireGuard interface = {{ wireguard_interface }}"

    - name: Verify both workers have UFW configured
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: UFW enabled = {{ has_ufw }}"

    - name: Check if UFW is installed
      ansible.builtin.command: which ufw
      register: ufw_check
      failed_when: false
      changed_when: false

    - name: Display UFW installation status
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: UFW installed = {{ ufw_check.rc == 0 }}"

    - name: Verify WireGuard IP assignments
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: WireGuard IP = {{ wireguard_ip }}"

    - name: Test dynamic IP resolution
      ansible.builtin.debug:
        msg: "Control plane public IP: {{ lookup('dig', hostvars[groups['control_plane'][0]]['ansible_host']) }}"
      run_once: true
